/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as PalavrasChaveRouteImport } from './routes/palavras-chave'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ReuniaoRouteImport } from './routes/reuniao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const PalavrasChaveRoute = PalavrasChaveRouteImport.update({
  id: '/palavras-chave',
  path: '/palavras-chave',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReuniaoRoute = ReuniaoRouteImport.update({
  id: '/reuniao',
  path: '/reuniao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mapa': typeof MapaRoute
  '/palavras-chave': typeof PalavrasChaveRoute
  '/radar': typeof RadarRoute
  '/reuniao': typeof ReuniaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mapa': typeof MapaRoute
  '/palavras-chave': typeof PalavrasChaveRoute
  '/radar': typeof RadarRoute
  '/reuniao': typeof ReuniaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mapa': typeof MapaRoute
  '/palavras-chave': typeof PalavrasChaveRoute
  '/radar': typeof RadarRoute
  '/reuniao': typeof ReuniaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/mapa' | '/palavras-chave' | '/radar' | '/reuniao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/mapa' | '/palavras-chave' | '/radar' | '/reuniao'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mapa'
    | '/palavras-chave'
    | '/radar'
    | '/reuniao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MapaRoute: typeof MapaRoute
  PalavrasChaveRoute: typeof PalavrasChaveRoute
  RadarRoute: typeof RadarRoute
  ReuniaoRoute: typeof ReuniaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palavras-chave': {
      id: '/palavras-chave'
      path: '/palavras-chave'
      fullPath: '/palavras-chave'
      preLoaderRoute: typeof PalavrasChaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reuniao': {
      id: '/reuniao'
      path: '/reuniao'
      fullPath: '/reuniao'
      preLoaderRoute: typeof ReuniaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MapaRoute: MapaRoute,
  PalavrasChaveRoute: PalavrasChaveRoute,
  RadarRoute: RadarRoute,
  ReuniaoRoute: ReuniaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
